name             'lxctests'
maintainer       'Chef Software, Inc.'
maintainer_email 'cookbooks@chef.io'
license          'Apache 2.0'
description      'Installs/Configures lxctests'
long_description 'Installs/Configures lxctests'
version          '0.1.0'

depends          'apt'
depends          'build-essential'
